#!/usr/bin/env python3
from pathlib import Path

t = Path("r2-pinskip.out").read_text()
print("LEN", len(t), "lines", t.count("\n"))
print(t[:5000])
print("\n==== MID TX_after ====")
i = t.find("TX_after_get_app")
print(t[i : i + 2500] if i >= 0 else "missing")
print("\n==== pack_r5 ====")
i = t.find("pack_r5_appstate")
print(t[i : i + 2500] if i >= 0 else "missing")
print("\n==== r2_0x11d6 ====")
i = t.find("r2_0x11d6")
print(t[i : i + 2000] if i >= 0 else "missing")
print("\n==== r2_0x347 ====")
i = t.find("MOVW r2,#0x347")
print(t[i : i + 500] if i >= 0 else "missing")
print("\n==== 347_near ====")
i = t.find("347_near_app")
print(t[i : i + 2000] if i >= 0 else "missing")
print("\n==== RatMap ====")
i = t.find("RatMap related")
print(t[i : i + 2000] if i >= 0 else "missing")
print("\n==== USIM 11d6 ====")
i = t.find("USIM window")
print(t[i : i + 1500] if i >= 0 else "missing")
