from pathlib import Path
for p in [
    Path("/tmp/saaios-vui07/crates/saai-ui-compiler/src/lib.rs"),
    Path("/tmp/saaios-vui07/crates/saai-ui-compiler/src/vocabulary.rs"),
    Path("/tmp/saaios-vui07/crates/saai-ui-compiler/src/rollback.rs"),
    Path("/tmp/saaios-vui07/crates/saai-ui-compiler/src/layout.rs"),
    Path("/tmp/saaios-vui07/services/saai-shell/build.rs"),
    Path("/tmp/saaios-vui07/crates/saai-ui-core/src/lib.rs"),
    Path("/tmp/saaios-vui07/crates/saai-ui-core/src/gallery.rs"),
    Path("/tmp/saaios-vui07/docs/os/ui/examples/now-public.sui"),
    Path("/tmp/saaios-vui07/docs/os/ui/examples/inbox-public.sui"),
    Path("/tmp/saaios-vui07/docs/os/ui/examples/spaces-public.sui"),
    Path("/tmp/saaios-vui07/docs/os/ui/examples/me-public.sui"),
    Path("/tmp/saaios-vui07/docs/os/ui/examples/wifi-public.sui"),
    Path("/tmp/saaios-vui07/docs/os/ui/examples/bluetooth-public.sui"),
    Path("/tmp/saaios-vui07/docs/os/ui/examples/trusted-privileged.sui"),
    Path("/tmp/saaios-vui07/docs/os/ui/examples/capability-privileged.sui"),
    Path("/tmp/saaios-vui07/docs/os/ui/vui09-verification.md"),
    Path("/tmp/saaios-vui07/docs/os/ui/vui09-known-limitations.md"),
    Path("/tmp/saaios-vui07/docs/os/ui/sui-v2-public-api.md"),
    Path("/tmp/saaios-vui07/docs/adr/ADR-217-vui09-v2-now-hits.md"),
    Path("/tmp/saaios-vui07/docs/adr/ADR-218-vui09-v2-live-lists.md"),
    Path("/tmp/saaios-vui07/crates/saai-ui-core/src/keyboard.rs"),
    Path("/tmp/saaios-vui07/services/saai-shell/src/hardware_keyboard.rs"),
    Path("/tmp/saaios-vui07/docs/os/ui/component-library-v1.md"),
    Path("/tmp/saaios-vui07/docs/adr/ADR-221-vui09-v2-overlay-hits.md"),
    Path("/tmp/saaios-vui07/docs/adr/ADR-222-vui09-keyboard-ime.md"),
    Path("/tmp/saaios-vui07/docs/adr/ADR-223-vui09-v2-orb-hits.md"),
    Path("/tmp/saaios-vui07/docs/adr/ADR-224-vui09-v2-diagnostic-hits.md"),
    Path("/tmp/saaios-vui07/docs/adr/ADR-225-vui09-now-paint.md"),
    Path("/tmp/saaios-vui07/docs/adr/ADR-226-vui09-list-paint.md"),
    Path("/tmp/saaios-vui07/docs/adr/ADR-227-vui09-me-paint.md"),
    Path("/tmp/saaios-vui07/docs/adr/ADR-228-vui09-apps-paint.md"),
    Path("/tmp/saaios-vui07/docs/adr/ADR-229-vui09-overlay-paint.md"),
    Path("/tmp/saaios-vui07/docs/adr/ADR-230-vui09-orb-paint.md"),
    Path("/tmp/saaios-vui07/docs/adr/ADR-231-vui09-diagnostic-paint.md"),
    Path("/tmp/saaios-vui07/docs/adr/ADR-232-vui09-leftover-formulas.md"),
    Path("/tmp/saaios-vui07/docs/os/sprints/PIXEL-PATH.md"),
    Path("/tmp/saaios-vui07/docs/os/sprints/README.md"),
    Path("/tmp/saaios-vui07/docs/os/sprints/VISUAL-ROADMAP.md"),
    Path("/tmp/saaios-vui07/services/saai-shell/ui/root.sui"),
    Path("/tmp/saaios-vui07/services/saai-shell/ui/now.sui"),
    Path("/tmp/saaios-vui07/services/saai-shell/src/main.rs"),
    Path("/tmp/saaios-vui07/services/saai-shell/src/render.rs"),
    Path("/tmp/saaios-vui07/services/saai-shell/src/haptic.rs"),
]:
    p.write_bytes(p.read_bytes().replace(b"\r\n", b"\n").replace(b"\r", b"\n"))
    print("lf", p, p.stat().st_size)
